require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlaylistsController do

  # This should return the minimal set of attributes required to create a valid
  # Playlist. As you add validations to Playlist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all playlists as @playlists" do
      playlist = Playlist.create! valid_attributes
      get :index
      assigns(:playlists).should eq([playlist])
    end
  end

  describe "GET show" do
    it "assigns the requested playlist as @playlist" do
      playlist = Playlist.create! valid_attributes
      get :show, :id => playlist.id.to_s
      assigns(:playlist).should eq(playlist)
    end
  end

  describe "GET new" do
    it "assigns a new playlist as @playlist" do
      get :new
      assigns(:playlist).should be_a_new(Playlist)
    end
  end

  describe "GET edit" do
    it "assigns the requested playlist as @playlist" do
      playlist = Playlist.create! valid_attributes
      get :edit, :id => playlist.id.to_s
      assigns(:playlist).should eq(playlist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Playlist" do
        expect {
          post :create, :playlist => valid_attributes
        }.to change(Playlist, :count).by(1)
      end

      it "assigns a newly created playlist as @playlist" do
        post :create, :playlist => valid_attributes
        assigns(:playlist).should be_a(Playlist)
        assigns(:playlist).should be_persisted
      end

      it "redirects to the created playlist" do
        post :create, :playlist => valid_attributes
        response.should redirect_to(Playlist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved playlist as @playlist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playlist.any_instance.stub(:save).and_return(false)
        post :create, :playlist => {}
        assigns(:playlist).should be_a_new(Playlist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Playlist.any_instance.stub(:save).and_return(false)
        post :create, :playlist => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested playlist" do
        playlist = Playlist.create! valid_attributes
        # Assuming there are no other playlists in the database, this
        # specifies that the Playlist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Playlist.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => playlist.id, :playlist => {'these' => 'params'}
      end

      it "assigns the requested playlist as @playlist" do
        playlist = Playlist.create! valid_attributes
        put :update, :id => playlist.id, :playlist => valid_attributes
        assigns(:playlist).should eq(playlist)
      end

      it "redirects to the playlist" do
        playlist = Playlist.create! valid_attributes
        put :update, :id => playlist.id, :playlist => valid_attributes
        response.should redirect_to(playlist)
      end
    end

    describe "with invalid params" do
      it "assigns the playlist as @playlist" do
        playlist = Playlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playlist.any_instance.stub(:save).and_return(false)
        put :update, :id => playlist.id.to_s, :playlist => {}
        assigns(:playlist).should eq(playlist)
      end

      it "re-renders the 'edit' template" do
        playlist = Playlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Playlist.any_instance.stub(:save).and_return(false)
        put :update, :id => playlist.id.to_s, :playlist => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested playlist" do
      playlist = Playlist.create! valid_attributes
      expect {
        delete :destroy, :id => playlist.id.to_s
      }.to change(Playlist, :count).by(-1)
    end

    it "redirects to the playlists list" do
      playlist = Playlist.create! valid_attributes
      delete :destroy, :id => playlist.id.to_s
      response.should redirect_to(playlists_url)
    end
  end

end
